### ISSUE TITLE
fix example in documentation >> annotations >> upload annotations

### ISSUE THREAD

**Issue by mromanello** [Savanamed/pycaprio#15]
First off, many thanks for `pycaprio`! The library API is very pythonic, a real pleasure to use :)

I believe that in this example

```python
from pycaprio.mappings import InceptionFormat, AnnotationState
with open("annotation") as annotation_file:
    new_annotation = client.api.create_annotation(1, 4, 'leonardo-dicaprio', annotation_format=InceptionFormat.WEBANNO, annotation_state=AnnotationState.ANNOTATION_IN_PROGRESS)
```

the fourth parameter of `create_annotation()` is actually missing (it should be the annotation content).

**Comment by JavierLuna** [comment]
You are right! Will change it ASAP :)

**Comment by JavierLuna** [comment]
[Done!](https://pycaprio.readthedocs.io/en/latest/api/annotations/#upload-annotation)

Thanks for the report!
