### ISSUE TITLE
support of CRUD operations for `curation`

### ISSUE THREAD

**Issue by mromanello** [Savanamed/pycaprio#23]
I've noticed that `pycaprio` does not currently support CRUD operations on curated documents, while INCEpTION has a dedicated API endpoint for that. 

Would you welcome a PR that adds such a feature to your library?

**Comment by JavierLuna** [comment]
Of course It'd be welcome!

I was in a rush and didn't have time to implement and test it properly, but I'd love to have that funcionality :)

**Comment by mromanello** [comment]
ok, great. Just to make sure I understand your library design: I'd start by adding the method `HttpInceptionAdapter.curation(...)`, right?

**Comment by JavierLuna** [comment]
You'd need to:

1. Create a `Curation` object with its properties in `pycaprio.core.objects`
2. Create a `curation` function (acting as a signature really) in `pycaprio.core.interfaces.adapter`
3. Create a `CurationSchema` in `pycaprio.core.schemas`. That will handle serialization-deserialization.
4. Implement the `curation` function in `pycaprio.adapters.http_adapters`, as you stated.

Then, add unit tests and that'd be it!

I'll try to add CONTRIB guidelines and community friendly files to ease the process.

Thank you so so much!

**Comment by jackmen** [comment]
Dear @mromanello ,

just to update you on this issue so you don't invest your time. We are currently working on implementing the curation option and we are only missing to add the tests and to check a possible bug with Inception. I opened an issue regarding the creation of curations in Inception: [https://github.com/inception-project/inception/issues/1657](url).

All the best,

Sebastian
