### ISSUE TITLE
Unable to upload ConLL 2003 file

### ISSUE THREAD

**Issue by ankur287** [Savanamed/pycaprio#36]
Hi Team,

I am not able to upload ConLL 2003 file to inception. I tried uploading ConLL2003 as document but when I tried to open it in inception, my browser is crashing. I am assuming it is because there are so many lines with 1 line for each word. I also tried uploading txt file as document and ConLL2003 file as annotations but it gives error.

Please help me in solving this problem. I have NER predictions for each word from the model and I want to upload that back to inception so that a person can coorect the model predictions and use new tags for model training.

**Comment by JavierLuna** [comment]
It seems like the file is correctly uploaded to INCEpTION, but for some reason INCEpTION isn't able to load it properly.
Pycaprio handles the upload of the file using INCEpTION's API internally, but doesn't operate on your file in any way, so I would suggest you to report a bug in [INCEpTION's bug tracker](https://github.com/inception-project/inception).

Thank you for the bug report anyway!
